{
    "th06 16bit textures": "Texturas em 16 Bit apenas",
    "th06 16bits mode": "16-bit",
    "th06 32bits mode": "32-bit",
    "th06 accept": "OK",
    "th06 Bomb Marisa A": "Amuleto Mágico 「Devaneio de Poeira Estelar」",
    "th06 Bomb Marisa B": "Amuleto do Amor 「Fagulha Exímia」",
    "th06 Bomb Reimu A": "Amuleto Espiritual 「Selo da Fantasia」",
    "th06 Bomb Reimu B": "Amuleto Onírico 「Círculo de Selar o Mal」",
    "th06 cancel": "Cancelar",
    "th06 check pad": "Checar entrada do pad",
    "th06 clear buffer": "Limpar back buffer ao atualizar",
    "th06 color composition": "Não aplicar composição das cores nas texturas",
    "th06 colors": "Modelo de Cor",
    "th06 config export failure": "Não consegue sobrepor o arquivo %s.\nPor acaso está no atributo read-only?",
    "th06 config saved caption": "OK",
    "th06 config saved text": "Configurações salvas.",
    "th06 config": "Touhou Koumakyou - Programa de Personalização de Ambiente",
    "th06 depth test": "Desligar teste de profundidade",
    "th06 DirectInput": "Não utilizar o DirectInput do pad",
    "th06 down": "Baixo ",
    "th06 fog": "Não utilizar névoa",
    "th06 force frame": "Forçar a 60 frames",
    "th06 full rate": "1/1 (padrão)",
    "th06 fullscreen": "Tela Cheia",
    "th06 Gouraud shading": "Impedir uso do sombreamento de Gouraud",
    "th06 half rate": "1/2",
    "th06 left": "Esquerda ",
    "th06 minimum graphics": "Mostrar gráficos mínimos se necessário",
    "th06 pad X axis": "Pad Eixo X (1–1000)",
    "th06 pad Y axis": "Pad Eixo Y (1–1000)",
    "th06 rasterizer mode": "Iniciar referindo-se ao modo de rasterização",
    "th06 refresh rate": "Pulo de Quadros",
    "th06 right": "Direita ",
    "th06 screen mode": "Tamanho da Janela",
    "th06 Stats MarisaA": "Marisa Kirisame (Mágico)",
    "th06 Stats MarisaB": "Marisa Kirisame (Amor)",
    "th06 Stats ReimuA": "Reimu Hakurei (Espiritual)",
    "th06 Stats ReimuB": "Reimu Hakurei (Onírico)",
    "th06 third rate": "1/3",
    "th06 up": "Cima ",
    "th06 vertex": "Não utilizar buffer vertex",
    "th06 windowed": "Janela",
    "th06_error_two_instances": "Não pode ter duas instâncias ao mesmo tempo.\n",
    "th06_log_16bit_textures": "Forçando texturas 16-bit.\n",
    "th06_log_backbuffer_nonlocking_suggestion": "Tentando fazer o back buffer não travável.\n",
    "th06_log_character_init_failure": "Error: falha ao inicializar Personagem.\n",
    "th06_log_clear_buffer": "Forçando limpeza do back buffer.\n",
    "th06_log_color_composition": "Não aplicando composição de cor.\n",
    "th06_log_depth_test": "Teste de profundidade está desligado.\n",
    "th06_log_direct3d_init_failure": "Erro ao inicializar o Direct3D, o jogo não consegue iniciar.\n",
    "th06_log_directinput_init": "DirectInput foi iniciado com sucesso.\n",
    "th06_log_directinput_usage": "Não utilizando DirectInput para pad ou teclado.\n",
    "th06_log_directsound_init": "DirectSound foi iniciado com sucesso.\n",
    "th06_log_export_failure": "Não consegue sobrepor o arquivo %s\n",
    "th06_log_first_startup_16bit": "Começando inicialização, iniciando a janela no modo de 16-bit.\n",
    "th06_log_first_startup_32bit": "Começando inicialização, iniciando a janela no modo de 32-bit.\n",
    "th06_log_fog": "Não utilizando a névoa.\n",
    "th06_log_force_frame": "Forçando a 60 FPS.\n",
    "th06_log_Gouraud_shading": "Impedindo o uso do sombreamento de Gouraud.",
    "th06_log_hal_unavailable": "CAH não está disponível.\n",
    "th06_log_header": "Registro de Controle Touhou --------------------------------------------- \n",
    "th06_log_minimum_graphics": "Impedindo a renderização dos itens no jogo.\n",
    "th06_log_no_gamepad": "Infelizmente, nenhum controle foi encontrado.\n",
    "th06_log_rasterizer_mode": "Iniciando Starting in reference rasterizer mode.\n",
    "th06_log_read_only_full_disk": "O arquivo está atribuído como read-only ou o disco está cheio?\n",
    "th06_log_refresh_rate": "Mudando a taxa de atualização para 60Hz.\n",
    "th06_log_reinit_corrupt_config": "O arquivo de configuração estava corrompido, e o programa reiniciou.\n",
    "th06_log_reinit_missing_config": "O arquivo de configuração estava faltando, e o programa reiniciou.\n",
    "th06_log_sound_file_read_error": "Error: arquivo de Som não conseguiu ser processado. Checar a data %s.\n",
    "th06_log_sprite_read_error": "Não consegue processar a animação dos sprites %s. Dados estão faltando ou corrompidos.",
    "th06_log_texture_read_error": "Não consegue processar a textura %s. Dados estão faltando ou corrompidos.",
    "th06_log_tl_hal_unavailable": "T&L CAH não está disponível.\n",
    "th06_log_tl_hal": "Trabalhando com T&L CAH.\n",
    "th06_log_unable_to_read_file": "Não consegue processar o arquivo %s.\n",
    "th06_log_valid_pad": "Um gamepad compatível foi encontrado.\n",
    "th06_log_vertex": "Não utilizando o buffer vertex.\n",
    "th06_log_window_mode": "Executando em modo de janela.\n",
    "th06": "Touhou Koumakyou ~ a Encarnação da Demônia Escarlate",
    "th07 16bits textures": "Forçar texturas de 16-bit",
    "th07 32bits mode": "32-bit (padrão)",
    "th07 BGM memory": "Pré-carregar Música de Fundo na memória",
    "th07 Bomb Marisa A focused": "Amuleto Mágico 「Via Láctea」",
    "th07 Bomb Marisa B unfocused": "Amuleto do Amor 「Laser Não-Direcional」",
    "th07 Bomb Reimu A focused": "Amuleto Espiritual 「Selo Fantasioso -Concentrar-」",
    "th07 Bomb Reimu A unfocused": "Amuleto Espiritual 「Selo Fantasioso -Espalhar-」",
    "th07 Bomb Reimu B focused": "Amuleto Onírico 「Barreira Dupla」",
    "th07 Bomb Sakuya A focused": "Relógio Ilusório 「Boneca Assassina」",
    "th07 Bomb Sakuya A unfocused": "Relógio Ilusório 「Indiscriminado」",
    "th07 Bomb Sakuya B focused": "Relógio Temporal 「Quadrado Particular」",
    "th07 Bomb Sakuya B unfocused": "Relógio Temporal 「Quadrado Perfeito」",
    "th07 config": "Touhou Youyoumu - Programa de Personalização de Ambiente",
    "th07 DirectInput": "Não utilizar o DirectInput do controle como dispositivo de entrada.",
    "th07 draw screen": "Redesenhar HUD a cada quadro",
    "th07 effect quality": "Qualidade dos Efeitos",
    "th07 fullscreen": "Tela Cheia (Recom.)",
    "th07 high effects": "Máx. (Recom.)",
    "th07 Key Bomb": "Definir botão de bomba/cancelar.",
    "th07 Key Down": "Definir botão para mover para baixo.",
    "th07 Key Left": "Definir botão para mover para a esquerda.",
    "th07 Key Pause": "Definir botão de pausa.",
    "th07 Key Quit": "Sair das configurações dos botões.",
    "th07 Key Reset": "Restaurar configurações padrões.",
    "th07 Key Right": "Definir botão para mover para a direita",
    "th07 Key Shot": "Definir botão de atirar/confirmar.",
    "th07 Key ShotSlow": "Mova devagar enquanto estiver segurando o botão de atirar.",
    "th07 Key Skip": "Definir botão de pular texto.",
    "th07 Key Slow": "Definir botão para reduzir movimentação.",
    "th07 Key Up": "Definir botão para mover para cima.",
    "th07 low effects": "Mín.",
    "th07 medium effects": "Moderado",
    "th07 Menu Extra Start": "Iniciar Estágio Extra",
    "th07 Menu Music Room": "Escutar músicas",
    "th07 Menu Option": "Alterar configurações",
    "th07 Menu Practice Start": "Selecionar um estágio e comece a praticar",
    "th07 Menu Quit": "Sair do jogo",
    "th07 Menu Replay": "Assistir replays",
    "th07 Menu Result": "Ver resultados das pontuações e spell cards",
    "th07 Menu Start": "Iniciar o jogo",
    "th07 Option BGM": "Alternar método de saída da Música de Fundo. (Padrão: WAV)",
    "th07 Option Graphic": "Alterar profundidade de cor da tela. 32-bits é o mais bonito.",
    "th07 Option Key Config": "Configurar controles do teclado",
    "th07 Option Player": "Escolha um número inicial de vidas para começar. (Padrão: 3)",
    "th07 Option Quit": "Sair do menu de configurações.",
    "th07 Option Reset": "Restaurar configurações padrões.",
    "th07 Option Slow Mode": "Câmera Lenta se tiver muitas balas. (Recorde e replay desativados)",
    "th07 Option Sound": "Escolher quando tocar os efeitos sonoros.",
    "th07 Option Window Mode": "Alternar entre tela cheia e janela.",
    "th07 Spell Result Character Select": "%s  Total %3d / Conseguiu %3d (Mudar Personagens↓↑)",
    "th07 Stats Clear Count +Phantasm": "<tl$N.º de Vezes Concluído\t$Reimu Hakurei (Espiritual)\t $Reimu Hakurei (Onírico)\t $Marisa Kirisame (Mágico)\t $Marisa Kirisame (Amor)\t $Sakuya Izayoi (Ilusório)\t $Sakuya Izayoi (Temporal)\t> %6d\t %6d\t %6d\t %6d\t %6d\t %6d\t %6d",
    "th07 Stats Clear Count": "<tl$N.º de Vezes Concluído\t\t\t\t\t\t\t\t\t\t\t> %6d\t %6d\t %6d\t %6d\t %6d\t %6d",
    "th07 Stats Continue +Phantasm": "<l$Continuar> %6d\t %6d\t %6d\t %6d\t %6d\t %6d\t %6d",
    "th07 Stats Continue": "<l$Continuar> %6d\t %6d\t %6d\t %6d\t %6d\t %6d",
    "th07 Stats Header Total": "Total",
    "th07 Stats MarisaA": "Marisa Kirisame (Mágico)",
    "th07 Stats MarisaB": "Marisa Kirisame (Amor)",
    "th07 Stats Play Count +Phantasm": "<tl$N.º de Vezes Jogado\t\t\t\t\t\t\t\t\t\t\t> Fácil\t Normal\t Difícil\t Insano\t Extra\t Fantasma\t Total",
    "th07 Stats Play Count": "<tl$N.º de Vezes Jogado\t$Reimu Hakurei (Espiritual)\t $Reimu Hakurei (Onírico)\t $Marisa Kirisame (Mágico)\t $Marisa Kirisame (Amor)\t $Sakuya Izayoi (Ilusório)\t $Sakuya Izayoi (Temporal)\t> Fácil\t Normal\t Difícil\t Insano\t Extra\t Total",
    "th07 Stats Practice +Phantasm": "<l$N.º de Práticas> %6d\t %6d\t %6d\t %6d\t %6d\t %6d\t %6d",
    "th07 Stats Practice": "<l$N.º de Práticas> %6d\t %6d\t %6d\t %6d\t %6d\t %6d",
    "th07 Stats ReimuA": "Reimu Hakurei (Espiritual)",
    "th07 Stats ReimuB": "Reimu Hakurei (Onírico)",
    "th07 Stats Retries +Phantasm": "<l$Tentativas> %6d\t %6d\t %6d\t %6d\t %6d\t %6d\t %6d",
    "th07 Stats Retries": "<l$Tentativas> %6d\t %6d\t %6d\t %6d\t %6d\t %6d",
    "th07 Stats SakuyaA": "Sakuya Izayoi (Ilusório)",
    "th07 Stats SakuyaB": "Sakuya Izayoi (Temporal)",
    "th07 Stats Time Since Startup": "<tl$Tempo desde a Inicialização>  %.2d:%.2d:%.2d",
    "th07 Stats Total (All Characters)": "Todas as Personagens",
    "th07 Stats Total Playtime": "<l$Tempo total de Jogo>  %.2d:%.2d:%.2d",
    "th07 VSync": "Desativar sincronização vertical",
    "th07_log_async_update_failure": "Atualizações assíncronas também não são possíveis. Alterando para o modo de menor fidelidade.\n",
    "th07_log_async_vsync_test": "Tentando ver se a sincronização vertical assíncrona é possível.\n",
    "th07_log_BGM_memory": "Pré-carregando Música de Fundo na memória.\n",
    "th07_log_draw_screen": "Redesenhando HUD a cada quadro.\n",
    "th07_log_refresh_rate_suggestion": "*** Recomenda-se alterar a taxa de atualização para 60 Hz ***\n",
    "th07_log_reinit_abNormalal_config": "O arquivo de configuração estava corrompido ou inválido, por isso foi reiniciado.\n",
    "th07_log_Vsync": "Sincronização vertical está desativada.\n",
    "th07": "Touhou Youyoumu ~ a Perfeita Flor de Cerejeira",
    "th08 Bomb Alice Last": "Títeretiço 「De Volta ao Inanimado」",
    "th08 Bomb Alice": "Performance 「Sacrifício Artístico」",
    "th08 Bomb Marisa Last": "Canhão da Carochinha 「Fagulha Final」",
    "th08 Bomb Reimu Last": "Espírito Divino 「Selo Fantasioso -Lampejo-」",
    "th08 Bomb Reimu": "Amuleto Espiritual 「Orbe da Fantasia」",
    "th08 Bomb Remilia Last": "Magia Escarlate 「Demônia Escarlate」",
    "th08 Bomb Remilia": "Marca Escarlate 「Vermelho seja o Castelo Sem Noite」",
    "th08 Bomb Sakuya Last": "Ilusão Fúnebre 「Assassina Fantasma da Névoa Noturna」",
    "th08 Bomb Youmu Last": "Oni Humana 「Corte do Eterno Futuro」",
    "th08 Bomb Youmu": "Humanidade 「Corte do Mundo Presente」",
    "th08 Bomb Yukari Last": "Barreira 「Barreira Quádrupla da Noite Imarcescível」",
    "th08 Bomb Yukari": "Magia Divisória 「Barreira Quádrupla」",
    "th08 Bomb Yuyuko Last": "Borboleta Mortífera 「Sono Eterno no Mundo dos Sonhos」",
    "th08 Bomb Yuyuko": "Assombração Mortal 「Sonho Tenebroso」",
    "th08 color composition": "Não utilize composição das cores nas texturas (proibido)",
    "th08 config": "Touhou Eiyashou - Programa de Personalização de Ambiente",
    "th08 depth test": "Desativar buffer de profundidade (não recomendado)",
    "th08 fog": "Desativar neblina (não recomendado)",
    "th08 Menu Spell Practice": "Praticar spell card contra uma oponente.",
    "th08 Music Room spoiler 1": "*** AVISO ***",
    "th08 Music Room spoiler 2": "Esta música ainda não foi tocada no jogo.",
    "th08 Music Room spoiler 3": "Se você não deseja ouvir a música ou ver os comentários, ",
    "th08 Music Room spoiler 4": "É recomendado que você saia daqui o mais breve possível.",
    "th08 Music Room spoiler 5": "　",
    "th08 Music Room spoiler 6": "(Adendo, tome cuidado, é possível apertar o botão de CONFIRMAR,",
    "th08 Music Room spoiler 7": "aqui para ver os comentários e tocar a música tema.)",
    "th08 Option BGM Volume": "Ajustar o volume da Música de Fundo",
    "th08 Option SE Volume": "Ajustar o volume dos efeitos sonoros.",
    "th08 rasterizer mode": "Iniciar no modo de rasterizador de referência (proibido)",
    "th08 Spell Condition Line 1 205": "Selecionável ao completar o Estágio Extra capturando 7 ou mais Spell Cards.",
    "th08 Spell Condition Line 1 206": "Selecionável ao completar o Final B com 2 ou mais Personagens.",
    "th08 Spell Condition Line 1 207": "Selecionável ao completar o Final B com 3 ou mais Personagens.",
    "th08 Spell Condition Line 1 208": "Selecionável quando 50 'Spell Cards' forem capturadas no modo 'Praticar Spell Card'.",
    "th08 Spell Condition Line 1 209": "Selecionável ao completar o Final B com 4 ou mais Personagens.",
    "th08 Spell Condition Line 1 210": "Selecionável quando a No.%.3d for adquirida.",
    "th08 Spell Condition Line 1 211": "Selecionável quando 15 'Última Spells' forem capturadas no modo 'Praticar Spell Card'.",
    "th08 Spell Condition Line 1 212": "Selecionável quando a No.%.3d,%.3d for adquirida.",
    "th08 Spell Condition Line 1 213": "Selecionável quando No.%.3d,%.3d,%.3d for vista pela primeira vez.",
    "th08 Spell Condition Line 1 214": "Selecionável quando No.%.3d,%.3d,%.3d,%.3d for vista pela primeira vez.",
    "th08 Spell Condition Line 1 215": "Selecionável quando todas as 'Spell Cards' da dificuldade Normal+ forem vistas",
    "th08 Spell Condition Line 1 216": "Selecionável ao completar a dificuldade Difícil ou Insana com a Reimu Solo.",
    "th08 Spell Condition Line 1 217": "Selecionável quando 120 'Spell Cards' forem capturadas no modo 'Praticar Spell Card'.",
    "th08 Spell Condition Line 1 218": "Selecionável ao completar o Final B com 6 ou mais Personagens.",
    "th08 Spell Condition Line 1 219": "Selecionável ao completar o Estágio Extra com 3 Personagens.",
    "th08 Spell Condition Line 1 220": "Selecionável quando 30 'Última Spells' forem capturadas no modo 'Praticar Spell Card'.",
    "th08 Spell Condition Line 1 221": "Selecionável ao completar na dificuldade Insano.",
    "th08 Spell Condition Line 1 222": "Selecionável quando todas as 'Últimas Spells' forem vistas pela primeira vez.",
    "th08 Spell Condition Line 2 205": "spell cards, incluindo da Keine.",
    "th08 Spell Condition Line 2 206 207 209": "dificuldade não importa.",
    "th08 Spell Condition Line 2 208 211 217 220": "Todas as Personagens combinadas.",
    "th08 Spell Condition Line 2 212": "e quando Nr.%.3d for vista pela primeira vez.",
    "th08 Spell Condition Line 2 213 214 222": "Não é necessário capturá-las.",
    "th08 Spell Condition Line 2 215": "com a Marisa Solo.",
    "th08 Spell Condition Line 2 216": "Necessário escolher o Final B.",
    "th08 Spell Condition Line 2 221": "Continuar/personagem não importa.",
    "th08 Spell Dissolve": "\"Desfazer Spell\"",
    "th08 Spell Practice Comment": "Comentários dos Cards",
    "th08 Spell Practice Description": "Estágio  Captura/Desbloqueado/Total (()Todas as Personagens no Total)",
    "th08 Spell Practice Easy Mode": "Praticar Spell (Fácil)",
    "th08 Spell Practice Extra Mode": "Praticar Spell (Extra)",
    "th08 Spell Practice Hard Mode": "Praticar Spell (Difícil)",
    "th08 Spell Practice Highscore Title": "Adquirido(s)/Confrontado(s)[Recorde]　%s　Todas as Personagens",
    "th08 Spell Practice Last Spell": "Última",
    "th08 Spell Practice Last Word": "Praticar Spell (Última Spell)",
    "th08 Spell Practice List Description": "Adquirido(s) / Confrontado(s) (Total da História Principal)",
    "th08 Spell Practice Lunatic Mode": "Praticar Spell (Insano)",
    "th08 Spell Practice Normal Mode": "Praticar Spell  (Normal)",
    "th08 Spell Practice Owner/Difficulty Line": "Propriedade de  %s　　%s %s",
    "th08 Spell Practice Percentages": "Taxa de Captura  (Personagens/No Geral)",
    "th08 Spell Result Character Select": "%3d/%3d (Mudar Personagens↓↑)",
    "th08 Spell Resurrection": "「Ressurreição」",
    "th08 Stats Alice": "Alice Margatroid",
    "th08 Stats Clear Count": "N.º de Vezes Concluído  %6d %6d %6d %6d %6d %6d",
    "th08 Stats Continue": "Continuar  %6d %6d %6d %6d %6d %6d",
    "th08 Stats Marisa & Alice": "Marisa & Alice",
    "th08 Stats Marisa": "Marisa Kirisame",
    "th08 Stats Play Count": "<tl$N.º de Vezes Jogado>        Fácil Normal Difícil Insano Extra Total",
    "th08 Stats Practice": "N.º de Práticas  %6d %6d %6d %6d %6d %6d",
    "th08 Stats Reimu & Yukari": "Reimu & Yukari",
    "th08 Stats Reimu": "Reimu Hakurei",
    "th08 Stats Remilia": "Remilia Scarlet",
    "th08 Stats Sakuya & Remilia": "Sakuya & Remilia",
    "th08 Stats Sakuya": "Sakuya Izayoi",
    "th08 Stats Time Since Startup": "<tl$Tempo desde a Inicialização>  %.2d:%.2d:%.2d",
    "th08 Stats Total (All Characters)": "Todas as Personagens",
    "th08 Stats Total Playtime": "<l$Tempo total de Jogo>  %.2d:%.2d:%.2d",
    "th08 Stats Youmu & Yuyuko": "Youmu & Yuyuko",
    "th08 Stats Youmu": "Youmu Konpaku",
    "th08 Stats Yukari": "Yukari Yakumo",
    "th08 Stats Yuyuko": "Yuyuko Saigyouji",
    "th08 VSync": "Desativar sincronização vertical (não recomendado)",
    "th08": "Touhou Eiyashou ~ A Noite Imarcescível",
}