{
    "th06 Bomb Reimu A": "Amuleto Espiritual 「Selo da Fantasia」",
    "th06 Bomb Reimu B": "Amuleto Onírico 「Círculo de Selar o Mal」",
    "th06 Bomb Marisa A": "Amuleto Mágico 「Devaneio de Poeira Estelar」",
    "th06 Bomb Marisa B": "Amuleto do Amor 「Fagulha Exímia」",
    "th06 config": "Touhou Koumakyou - Programa de Personalização de Ambiente",
    "th06 up": "Cima ",
    "th06 down": "Baixo ",
    "th06 left": "Esquerda ",
    "th06 right": "Direita ",
    "th06 vertex": "Não usar buffer vertex",
    "th06 fog": "Não usar névoa",
    "th06 16bit textures": "Texturas em 16 Bit apenas",
    "th06 Gouraud shading": "Impedir uso do sombreamento de Gouraud",
    "th06 color composition": "Não aplicar composição das cores nas texturas",
    "th06 rasterizer mode": "Iniciar referindo-se ao modo de rasterização",
    "th06 clear buffer": "Limpar back buffer ao atualizar",
    "th06 minimum graphics": "Mostrar gráficos mínimos se necessário",
    "th06 depth test": "Desligar teste de profundidade",
    "th06 force frame": "Forçar a 60 frames",
    "th06 fullscreen": "Tela Cheia",
    "th06 windowed": "Janela",
    "th06 full rate": "1/1 (padrão)",
    "th06 half rate": "1/2",
    "th06 third rate": "1/3",
    "th06 32bits mode": "32-bit",
    "th06 16bits mode": "16-bit",
    "th06 accept": "OK",
    "th06 cancel": "Cancelar",
    "th06 screen mode": "Tamanho da Janela",
    "th06 refresh rate": "Pulo de Quadros",
    "th06 colors": "Modelo de Cor",
    "th06 pad X axis": "Pad Eixo X (1–1000)",
    "th06 pad Y axis": "Pad Eixo Y (1–1000)",
    "th06 check pad": "Checar entrada do pad",
    "th06 DirectInput": "Não usar o DirectInput do pad",
    "th06 config saved caption": "OK",
    "th06 config saved text": "Configurações salvas.",
    "th06 Stats ReimuA": "Reimu Hakurei (Espiritual)",
    "th06 Stats ReimuB": "Reimu Hakurei (Onírico)",
    "th06 Stats MarisaA": "Marisa Kirisame (Mágico)",
    "th06 Stats MarisaB": "Marisa Kirisame (Amor)",
    "th06": "Touhou Terra da Demônia Escarlate ~ a Encarnação da Demônia Escarlate",
    "th06_log_header": "Registro de Controle Touhou --------------------------------------------- \n",
    "th06_error_two_instances": "Não pode ter duas instâncias ao mesmo tempo.\n",
    "th06_log_tl_hal": "Trabalhando com T&L CAH.\n",
    "th06_log_directsound_init": "DirectSound foi iniciado com sucesso.\n",
    "th06_log_no_gamepad": "Infelizmente, nenhum controle foi encontrado.\n",
    "th06_log_valid_pad": "Um gamepad compatível foi encontrado.\n",
    "th06_log_unable_to_read_file": "Não consegue processar o arquivo %s.\n",
    "th06_log_directinput_init": "DirectInput foi iniciado com sucesso.\n",
    "th06_log_sound_file_read_error": "Error: arquivo de Som não conseguiu ser processado. Checar a data %s.\n",
    "th06_log_texture_read_error": "Não consegue processar a textura %s. Dados estão faltando ou corrompidos.",
    "th06_log_sprite_read_error": "Não consegue processar a animação dos sprites %s. Dados estão faltando ou corrompidos.",
    "th06_log_export_failure": "Não consegue sobrepor o arquivo %s\n",
    "th06_log_read_only_full_disk": "O arquivo está atribuído como read-only ou o disco está cheio?\n",
    "th06_log_reinit_corrupt_config": "O arquivo de configuração estava corrompido, e o programa reiniciou.\n",
    "th06_log_reinit_missing_config": "O arquivo de configuração estava faltando, e o programa reiniciou.\n",
    "th06_log_first_startup_16bit": "Começando inicialização, iniciando a janela no modo de 16-bit.\n",
    "th06_log_first_startup_32bit": "Começando inicialização, iniciando a janela no modo de 32-bit.\n",
    "th06_log_character_init_failure": "Error: falha ao inicializar Personagem.\n",
    "th06_log_tl_hal_unavailable": "T&L CAH não está disponível.\n",
    "th06_log_hal_unavailable": "CAH não está disponível.\n",
    "th06_log_backbuffer_nonlocking_suggestion": "Tentando fazer o back buffer não travável.\n",
    "th06_log_direct3d_init_failure": "Erro ao inicializar o Direct3D, o jogo não consegue iniciar.\n",
    "th06_log_refresh_rate": "Mudando a taxa de atualização para 60Hz.\n",
    "th06_log_vertex": "Não utilizando o buffer vertex.\n",
    "th06_log_fog": "Não utilizando a névoa.\n",
    "th06_log_16bit_textures": "Forçando texturas 16-bit.\n",
    "th06_log_Gouraud_shading": "Impedindo o uso do sombreamento de Gouraud.",
    "th06_log_color_composition": "Não aplicando composição de cor.\n",
    "th06_log_rasterizer_mode": "Iniciando Starting in reference rasterizer mode.\n",
    "th06_log_clear_buffer": "Forçando limpeza do back buffer.\n",
    "th06_log_minimum_graphics": "Impedindo a renderização dos itens no jogo.\n",
    "th06_log_depth_test": "Teste de profundidade está desligado.\n",
    "th06_log_force_frame": "Forçando a 60 FPS.\n",
    "th06_log_directinput_usage": "Não utilizando DirectInput para pad ou teclado.\n",
    "th06_log_window_mode": "Executando em modo de janela.\n",
    "th06 config export failure": "Não consegue sobrepor o arquivo %s.\nPor acaso está no atributo read-only?",
}