{
    "th06_01": "A Dream More Scarlet than Red",
    "th06_02": "A Soul as Scarlet as a Ground Cherry",
    "th06_03": "Apparitions Stalk the Night",
    "th06_04": "Lunate Elf",
    "th06_05": "Tomboyish Girl in Love",
    "th06_06": "Shanghai Scarlet Teahouse ~ Chinese Tea",
    "th06_07": "Shanghai Alice of Meiji 17",
    "th06_08": "Voile, the Magic Library",
    "th06_09": "Locked Girl ~ The Girl's Sealed Room",
    "th06_10": "The Maid and the Pocket Watch of Blood",
    "th06_11": "Lunar Clock ~ Luna Dial",
    "th06_12": "The Young Descendant of Țepeș",
    "th06_13": "Septette for a Dead Princess",
    "th06_14": "The Centennial Festival for Magical Girls",
    "th06_15": "U.N. Owen was Her?",
    "th06_16": "An Eternity More Transient than Scarlet",
    "th06_17": "Scarlet Tower ~ Eastern Dream...",
    "th07_01": "Ghostly Dream ~ Snow or Cherry Petal",
    "th07_02": "Paradise ~ Deep Mountain",
    "th07_03": "Crystallized Silver",
    "th07_04": "The Fantastic Tales from Tōno",
    "th07_05": "Diāo Yè Zōng (withered leaf)",
    "th07_06": "The Doll Maker of București",
    "th07_07": "Doll Judgment ~ The Girl Who Played with People's Shapes",
    "th07_08": "The Capital City of Flowers in the Sky",
    "th07_09": "Phantom Band ~ Phantom Ensemble",
    "th07_10": "Eastern Ghostly Dream ~ Ancient Temple",
    "th07_11": "Hiroari Shoots a Strange Bird ~ Till When?",
    "th07_12": "Ultimate Truth",
    "th07_13": "Bloom Nobly, Ink-Black Cherry Blossom ~ Border of Life",
    "th07_14": "Border of Life",
    "th07_15": "Spiritual Domination",
    "th07_16": "A Maiden's Illusionary Funeral ~ Necro-Fantasy",
    "th07_17": "Spiritual Domination ~ Who done it!",
    "th07_18": "Necrofantasia",
    "th07_19": "Dream of a Spring Breeze",
    "th07_20": "Sakura, Sakura ~ Japanize Dream...",
    "th08_01": "Eternal Night Vignette ~ Eastern Night",
    "th08_02": "Illusionary Night ~ Ghostly Eyes",
    "th08_03": "Wriggling Autumn Moon ~ Mooned Insect",
    "th08_04": "Song of the Night Sparrow ~ Night Bird",
    "th08_05": "Deaf to All but the Song",
    "th08_06": "Nostalgic Blood of the East ~ Old World",
    "th08_07": "Plain Asia",
    "th08_08": "Retribution for the Eternal Night ~ Imperishable Night",
    "th08_09": "Maiden's Capriccio ~ Dream Battle",
    "th08_10": "Love-Colored Master Spark",
    "th08_11": "Cinderella Cage ~ Kagome-Kagome",
    "th08_12": "Lunatic Eyes ~ Invisible Full Moon",
    "th08_13": "Voyage 1969",
    "th08_14": "Gensokyo Millennium ~ History of the Moon",
    "th08_15": "Flight of the Bamboo Cutter ~ Lunatic Princess",
    "th08_16": "Voyage 1970",
    "th08_17": "Extend Ash ~ Person of Hourai",
    "th08_18": "Reach for the Moon, Immortal Smoke",
    "th08_19": "Evening Primrose",
    "th08_20": "Eternal Dream ~ Mystical Maple",
    "th08_21": "Eastern Youkai Beauty",
}