{
    "th06_01": "A Dream More Scarlet than Red",
    "th06_02": "A Soul as Scarlet as a Ground Cherry",
    "th06_03": "Apparitions Stalk the Night",
    "th06_04": "Lunate Elf",
    "th06_05": "Tomboyish Girl in Love",
    "th06_06": "Shanghai Scarlet Teahouse ~ Chinese Tea",
    "th06_07": "Shanghai Alice of Meiji 17",
    "th06_08": "Voile, the Magic Library",
    "th06_09": "Locked Girl ~ The Girl's Sealed Room",
    "th06_10": "The Maid and the Pocket Watch of Blood",
    "th06_11": "Lunar Clock ~ Luna Dial",
    "th06_12": "The Young Descendant of Țepeș",
    "th06_13": "Septette for a Dead Princess",
    "th06_14": "The Centennial Festival for Magical Girls",
    "th06_15": "U.N. Owen was Her?",
    "th06_16": "An Eternity More Transient than Scarlet",
    "th06_17": "Scarlet Tower ~ Eastern Dream...",
}