{
    "0": "Lúmen Pirilampo 「Meteoro Terrestre」",
    "1": "Lúmen da Pirilampo 「Cometa Terrestre」",
    "2": "Lúmen da Lamparina 「Fenômeno dos Vaga-Lumes」",
    "3": "Lúmen da Lamparina 「Fenômeno dos Vaga-Lumes」",
    "4": "Lúmen da Lamparina 「Fenômeno dos Vaga-Lumes」",
    "5": "Lúmen da Lamparina 「Fenômeno dos Vaga-Lumes」",
    "6": "Lúmen Contorcente 「Bichinhos」",
    "7": "Lúmen Contorcente 「Enxame de Bichinhos」",
    "8": "Lúmen Contorcente 「Enxame de Insetos Notívagos」",
    "9": "Lúmen Contorcente 「Infestação de Insetos Notívagos」",
    "10": "Inseto Camuflado 「Retiro na Noite Sem Fim」",
    "11": "Inseto Camuflado 「Retiro na Noite Sem Fim」",
    "12": "Inseto Camuflado 「Retiro na Noite Sem Fim」",
    "13": "Magia Vocal 「Chirriar da Noite」",
    "14": "Magia Vocal 「Chirriar da Noite」",
    "15": "Magia Vocal 「Corujar do Corujão」",
    "16": "Magia Vocal 「Corujar do Corujão」",
    "17": "Magia da Mariposa 「Maldição da Mariposa-falcão」",
    "18": "Magia da Mariposa 「Maldição da Mariposa-falcão」",
    "19": "Magia Tóxica 「Escamas Venenosas da Mariposa」",
    "20": "Toxina Letal 「Dança Notívaga da Mariposa Venenosa」",
    "21": "Magia do Falcão 「Rasante de Mau Agouro」",
    "22": "Magia do Falcão 「Rasante de Mau Agouro」",
    "23": "Magia do Falcão 「Rasante de Mau Agouro」",
    "24": "Magia do Falcão 「Rasante de Mau Agouro」",
    "25": "Cegueira Noturna 「Canto da Yosuzume」",
    "26": "Cegueira Noturna 「Canto da Yosuzume」",
    "27": "Cegueira Noturna 「Canto da Yosuzume」",
    "28": "Cegueira Noturna 「Canto da Yosuzume」",
    "29": "Pardal da Noite 「Maestra do Coro da Meia Noite」",
    "30": "Pardal da Noite 「Maestra do Coro da Meia Noite」",
    "31": "Pardal da Noite 「Maestra do Coro da Meia Noite」",
    "32": "Nascente Espiritual 「Primeira Pirâmide」",
    "33": "Nascente Espiritual 「Primeira Pirâmide」",
    "34": "Nascente Espiritual 「Primeira Pirâmide」",
    "35": "Nascente Espiritual 「Primeira Pirâmide」",
    "36": "Registro de Origem 「Efemeridade 137」",
    "37": "Registro de Origem 「Efemeridade 137」",
    "38": "Registro de Origem 「Efemeridade 137」",
    "39": "Registro de Ambição 「Crise de Buretsu」",
    "40": "Registro de Ambição 「Crise de Masakado」",
    "41": "Registro de Ambição 「Crise de Yoshimitsu」",
    "42": "Registro de Ambição 「Crise do Grande QG」",
    "43": "Registro de Terras 「Os 3 Tesouros Sagrados - Espada」",
    "44": "Registro de Terras 「Os 3 Tesouros Sagrados - Orbe」",
    "45": "Registro de Terras 「Os 3 Tesouros Sagrados - Espelho」",
    "46": "Esquema de Terras 「Os 3 Tesouros Sagrados - País」",
    "47": "Esquema Final 「O Imperador Espectral」",
    "48": "Esquema Final 「O Imperador Espectral」",
    "49": "Pseudo-História 「O Mito de Gensokyo」",
    "50": "Pseudo-História 「O Mito de Gensokyo」",
    "51": "Futuro 「O Reino dos Deuses」",
    "52": "Futuro 「O Reino dos Deuses」",
    "53": "Futuro 「O Reino dos Deuses」",
    "54": "Amuleto Onírico 「Barreira Dupla」",
    "55": "Amuleto Onírico 「Barreira Dupla」",
    "56": "Divisa Onírica 「Vasta Barreira Dupla」",
    "57": "Divisa Onírica 「Vasta Barreira Dupla」",
    "58": "Amuleto Espiritual 「Selo Fantasioso -Espalhar-」",
    "59": "Amuleto Espiritual 「Selo Fantasioso -Espalhar-」",
    "60": "Dispersão Espiritual 「Selo Fantasioso -Sabi-」",
    "61": "Dispersão Espiritual 「Selo Fantasioso -Sabi-」",
    "62": "Amuleto Onírico 「Círculo de Selar o Mal」",
    "63": "Amuleto Onírico 「Círculo de Selar o Mal」",
    "64": "Arte Divina 「Círculo Omnidirecional de Selar Oni」",
    "65": "Arte Divina 「Círculo Omnidirecional de Matar Dragões」",
    "66": "Amuleto Espiritual 「Selo Fantasioso -Concentrar-」",
    "67": "Amuleto Espiritual 「Selo Fantasioso -Concentrar-」",
    "68": "Exorcírculo Espiritual 「Selo Fantasioso -Wabi-」",
    "69": "Exorcírculo Espiritual 「Selo Fantasioso -Wabi-」",
    "70": "Divisa 「Barreira Danmaku Dupla」",
    "71": "Divisa 「Barreira Danmaku Dupla」",
    "72": "Vasta Barreira 「Barreira Danmaku Hakurei」",
    "73": "Vasta Barreira 「Barreira Danmaku Hakurei」",
    "74": "Espírito Divino 「Selo Fantasioso -Lampejo-」",
    "75": "Espírito Divino 「Selo Fantasioso -Lampejo-」",
    "76": "Espírito Divino 「Selo Fantasioso -Lampejo-」",
    "77": "Amuleto Mágico 「Via Láctea」",
    "78": "Amuleto Mágico 「Via Láctea」",
    "79": "Magia do Espaço Sideral 「Cinturão de Asteróides」",
    "80": "Magia do Espaço Sideral 「Cinturão de Asteróides」",
    "81": "Amuleto Mágico 「Devaneio de Poeira Estelar」",
    "82": "Amuleto Mágico 「Devaneio de Poeira Estelar」",
    "83": "Magia Negra 「Enigma do Horizonte」",
    "84": "Magia Negra 「Enigma do Horizonte」",
    "85": "Amuleto do Amor 「Laser Não-Direcional」",
    "86": "Amuleto do Amor 「Laser Não-Direcional」",
    "87": "Tempestade Amorosa 「Tufão Estelar」",
    "88": "Tempestade Amorosa 「Tufão Estelar」",
    "89": "Amuleto Mágico 「Fagulha Exímia」",
    "90": "Amuleto Mágico 「Fagulha Exímia」",
    "91": "Coração Amável 「Fagulha Dupla」",
    "92": "Coração Amável 「Fagulha Dupla」",
    "93": "Amuleto de Luz 「Raio da Luz Terrestre」",
    "94": "Amuleto de Luz 「Raio da Luz Terrestre」",
    "95": "Explosão de Luz 「Atirar na Lua」",
    "96": "Explosão de Luz 「Atirar na Lua」",
    "97": "Canhão da Carochinha 「Fagulha Final」",
    "98": "Canhão da Carochinha 「Fagulha Final」",
    "99": "Canhão da Carochinha 「Fagulha Exímia Final」",
    "100": "Alteração das Ondas 「Hipnose dos Olhos Vermelhos (Abalante)」",
    "101": "Alteração das Ondas 「Hipnose dos Olhos Vermelhos (Abalante)」",
    "102": "Ondas Ilusórias 「Hipnose dos Olhos Vermelhos (Alucinante)」",
    "103": "Ondas Ilusórias 「Hipnose dos Olhos Vermelhos (Alucinante)」",
    "104": "Alteração do Desvario 「Ajuste Alucinógeno (Ajuste Visionário)」",
    "105": "Alteração do Desvario 「Ajuste Alucinógeno (Ajuste Visionário)」",
    "106": "Olhar Insano 「Ajuste do Olhar Insano (Busca-Ilusão)」",
    "107": "Olhar Insano 「Ajuste do Olhar Insano (Busca-Ilusão)」",
    "108": "Alteração Preguiçosa 「Parada de Espírito e da Vida (Onda Indolenta)」",
    "109": "Alteração Preguiçosa 「Parada de Espírito e da Vida (Onda Indolenta)」",
    "110": "Indolência 「Parada de Espírito e da Vida (Parada Mental)」",
    "111": "Indolência 「Parada de Espírito e da Vida (Parada Mental)」",
    "112": "Alteração Expandida 「Lua da Verdade (Lua Cheia Invisível)」",
    "113": "Alteração Expandida 「Lua da Verdade (Lua Cheia Invisível)」",
    "114": "Alteração Expandida 「Lua da Verdade (Lua Cheia Invisível)」",
    "115": "Alteração Expandida 「Lua da Verdade (Lua Cheia Invisível)」",
    "116": "Olhos Lunares 「Mesmerizar Remoto da Coelha Lunar (Tele-Mesmerismo)」",
    "117": "Olhos Lunares 「Mesmerizar Remoto da Coelha Lunar (Tele-Mesmerismo)」",
    "118": "Olhos Lunares 「Mesmerizar Remoto da Coelha Lunar (Tele-Mesmerismo)」",
    "119": "Espaçosfera 「Terra em um Vaso」",
    "120": "Espaçosfera 「Terra em um Vaso」",
    "121": "Espaçosfera 「Terra em um Vaso」",
    "122": "Espaçosfera 「Terra em um Vaso」",
    "123": "Deusa Desperta 「Memórias da Era dos Deuses」",
    "124": "Deusa Desperta 「Memórias da Era dos Deuses」",
    "125": "Shinpu 「Genealogia dos Seres Celestiais」",
    "126": "Shinpu 「Genealogia dos Seres Celestiais」",
    "127": "Ressurreição 「Vida do Jogo -Jogo da Vida-」",
    "128": "Ressurreição 「Vida do Jogo -Jogo da Vida-」",
    "129": "Ressurreição 「Jogo de Ascender às Nuvens」",
    "130": "Ressurreição 「Jogo de Ascender às Nuvens」",
    "131": "Providência Divina 「Dispositivo do Omoikane」",
    "132": "Providência Divina 「Dispositivo do Omoikane」",
    "133": "Cérebro Divino 「Cérebro do Omoikane」",
    "134": "Cérebro Divino 「Cérebro do Omoikane」",
    "135": "Maldição Celeste 「Apollo 13」",
    "136": "Maldição Celeste 「Apollo 13」",
    "137": "Maldição Celeste 「Apollo 13」",
    "138": "Maldição Celeste 「Apollo 13」",
    "139": "Ocultismo 「Passada de Pano Astronômica」",
    "140": "Ocultismo 「Passada de Pano Astronômica」",
    "141": "Ocultismo 「Passada de Pano Astronômica」",
    "142": "Ocultismo 「Passada de Pano Astronômica」",
    "143": "Medicina Proibida 「Elixir de Hōrai」",
    "144": "Medicina Proibida 「Elixir de Hōrai」",
    "145": "Medicina Proibida 「Elixir de Hōrai」",
    "146": "Medicina Proibida 「Elixir de Hōrai」",
    "147": "Seta Medicinal 「Galáxia em um Vaso」",
    "148": "Seta Medicinal 「Galáxia em um Vaso」",
    "149": "Seta Medicinal 「Galáxia em um Vaso」",
    "150": "Seta Medicinal 「Galáxia em um Vaso」",
    "151": "Tarefa Impossível 「Joia do Pescoço do Dragão -Tiro de Cinco Cores-」",
    "152": "Tarefa Impossível 「Joia do Pescoço do Dragão -Tiro de Cinco Cores-」",
    "153": "Tesouro Divino 「Munição Brilhante do Dragão」",
    "154": "Tesouro Divino 「Munição Brilhante do Dragão」",
    "155": "Tarefa Impossível 「Bacia de Pedra do Buda -Vontade Indomável-」",
    "156": "Tarefa Impossível 「Bacia de Pedra do Buda -Vontade Indomável-」",
    "157": "Tesouro Divino 「Diamante Budista」",
    "158": "Tesouro Divino 「Diamante Budista」",
    "159": "Tarefa Impossível 「Manto do Rato de Fogo -Mente Paciente-」",
    "160": "Tarefa Impossível 「Manto do Rato de Fogo -Mente Paciente-」",
    "161": "Tesouro Divino 「Escudo Salamandra」",
    "162": "Tesouro Divino 「Escudo Salamandra」",
    "163": "Tarefa Impossível 「Búzio da Andorinha -Vida Mais que Longa-」",
    "164": "Tarefa Impossível 「Búzio da Andorinha -Vida Mais que Longa-」",
    "165": "Tesouro Divino 「Fonte da Vida Eterna」",
    "166": "Tesouro Divino 「Fonte da Vida Eterna」",
    "167": "Tarefa Impossível 「Bala de Ramo de Hōrai  -Danmaku Arco-íris-」",
    "168": "Tarefa Impossível 「Bala de Ramo de Hōrai  -Danmaku Arco-íris-」",
    "169": "Tesouro Divino 「Ramo Cravejado de Hōrai  -Paraíso dos Sonhos-」",
    "170": "Tesouro Divino 「Ramo Cravejado de Hōrai  -Paraíso dos Sonhos-」",
    "171": "「Retorno da Noite Eterna -Lua Nova-」",
    "172": "「Retorno da Noite Eterna -Lua Crescente-」",
    "173": "「Retorno da Noite Eterna -Lua Minguante-」",
    "174": "「Retorno da Noite Eterna -Matsuyoi-」",
    "175": "「Retorno da Noite Eterna -Onze da noite-」",
    "176": "「Retorno da Noite Eterna -Onze e meia-」",
    "177": "「Retorno da Noite Eterna -Meia Noite-」",
    "178": "「Retorno da Noite Eterna -Meia Noite e Meia-」",
    "179": "「Retorno da Noite Eterna -Uma da Manhã-」",
    "180": "「Retorno da Noite Eterna -Uma e Meia da Manhã-」",
    "181": "「Retorno da Noite Eterna -Duas da Manhã-」",
    "182": "「Retorno da Noite Eterna -Duas e Meia da Manhã-」",
    "183": "「Retorno da Noite Eterna -Três da Manhã-」",
    "184": "「Retorno da Noite Eterna -Três e Meia da Manhã-」",
    "185": "「Retorno da Noite Eterna -Quatro da Manhã-」",
    "186": "「Retorno da Noite Eterna -Quatro e Meia da Manhã-」",
    "187": "「Retorno da Noite Eterna -Orvalho da Manhã-」",
    "188": "「Retorno da Noite Eterna -Amanhecer-」",
    "189": "「Retorno da Noite Eterna -Estrela da Manhã-」",
    "190": "「Retorno da Noite Eterna -O Mundo Acorda-」",
    "191": "Memória 「História de Terras Antigas Inexploradas -História Antiga-」",
    "192": "Reencarnação 「Ponte Ichijo-Modoribashi」",
    "193": "História Futura 「Nova História de Fantasia -Próxima História-」",
    "194": "Prescrição 「Maldição do Tsuki-no-Iwakasa」",
    "195": "Imortal 「Pássaro de Fogo -Ave Fênix-」",
    "196": "Fujiwara 「Transgressões do Templo da Absolvição」",
    "197": "Imortal 「Espaço-Tempo Xu Fu」",
    "198": "Expiação 「A Morte de um Homem Honesto」",
    "199": "Pessoa Vazia 「Wu」",
    "200": "Inextinguível 「Penugem de Fênix」",
    "201": "Penglai 「Vento Firme, Manhã Clara -Vulcão Fujiyama-」",
    "202": "「Possuída pela Fênix」",
    "203": "「Boneca Hōrai」",
    "204": "「Tiroteio Imarcescível」",
    "205": "「Tempestade de Borboletas Fora de Temporada」",
    "206": "「Pássaro da Cegueira Noturna」",
    "207": "「Imperador da Terra do Sol Nascente」",
    "208": "「Olhar da Lua Ilusória (Olhos Vermelhos Insanos)」",
    "209": "「Teia da Aranha Celestial de Capturar Borboletas」",
    "210": "「Mar de Árvores de Hōrai」",
    "211": "「Renascimento da Fênix」",
    "212": "「Capciosa das Antigas」",
    "213": "「Chegar ao Completo Nada pela Purificação」",
    "214": "「Ambição Inata」",
    "215": "「Estrela Resplandecente」",
    "216": "「Mundo Descomprimido」",
    "217": "「Espera pela Noite para o Corte da Lua」",
    "218": "「O Fantasma do Grande Guinhol」",
    "219": "「Destino Escarlate」",
    "220": "「Parinirvana Saigyouji」",
    "221": "「Profunda Barreira Danmaku -Bolha de Sonho, Vazia e Efêmera -」",
}