{
    "0": "Magia do Luar 「Raio de Luar」",
    "1": "Magia da Noite 「Pássaro Notívago」",
    "2": "Magia da Escuridão 「Demarcação」",
     "3": "Magia de Gelo 「Estalactite de Gelo」",
    "4": "Magia de Granizo 「Tempestade de Granizo」",
    "5": "Magia de Congelamento 「Congelamento Perfeito!」",
    "6": "Magia de Neve 「Nevasca de Diamante」",
    "7": "Qi Floral 「Linda Doce Flor」",
    "8": "Qi Floral 「Selaginella 9」",
    "9": "Qi Arco-Íris 「Sinos de Vento Coloridos pelo Arco-Íris」",
    "10": "Qi Ilusório 「Flor Imaginária Yumekasura」",
    "11": "Qi Colorido 「Chuva Colorida」",
    "12": "Qi Colorido 「Vívida Dança Caótica」",
    "13": "Qi Colorido 「Tufão de Cores Estonteantes」",
    "14": "Livro de Fogo 「Brilho de Agni」",
    "15": "Livro de Água 「Princesa Ondina」",
    "16": "Livro de Madeira 「Chifre Sílfide」",
    "17": "Livro de Terra 「Trilito Preguiçoso」",
    "18": "Livro de Metal 「Fadiga de Metal」",
    "19": "Livro de Fogo 「Brilho de Agni de Alto Nível」",
    "20": "Livro de Madeira 「Chifre Sílfide de Alto Nível」",
    "21": "Livro de Terra 「Trilito Preguiçoso de Alto Nível」",
    "22": "Livro de Fogo 「Radiância de Agni」",
    "23": "Livro de Água 「Afundar no Lago」",
    "24": "Livro de Madeira 「Tempestade Verdejante」",
    "25": "Livro de Terra 「Sacolejo do Trilito」",
    "26": "Livro de Metal 「Dragão Prateado」",
    "27": "Livros de Fogo & Terra 「Cromeleque de Lava」",
    "28": "Livro de Madeira & Fogo 「Incêndio Florestal」",
    "29": "Livro de Água & Madeira 「Ninfa D'Água」",
    "30": "Livro de Metal & Água 「Envenenamento por Mercúrio」",
    "31": "Livro de Terra & Metal 「Megalítico de Esmeralda」",
    "32": "Conjurando 「Despistar」",
    "33": "Conjurando 「Despistar Fascinante」",
    "34": "Existência Ilusória 「Cadáver do Relógio」",
    "35": "Imagem Ilusória 「Relógio Lunar」",
    "36": "Truque Secreto da Camareira 「Boneca Manipuladora」",
    "37": "Fantasma Ilusório 「Jack, Ludo Bile」",
    "38": "Mundo Ilusório 「O Mundo」",
    "39": "Truque Secreto da Camareira 「Boneca Assassina」",
    "40": "Conjurando 「Eterna Mansidão」",
    "41": "Punição do Paraíso Perdido 「Estrela de Davi」",
    "42": "Marca dos Quintos 「Inferno Escarlate」",
    "43": "Maldição 「Maldição de Vlad Țepeș」",
    "44": "Marca Escarlate 「Tiro Escarlate」",
    "45": "「Magia Vermelha」",
    "46": "Punição Divina 「Jovem Senhora Demoníaca」",
    "47": "Marca do Inferno 「Montanha de 1000 Agulhas」",
    "48": "Arte Divina 「Ilusão da Vampira」",
    "49": "Marca Escarlate 「Mestra Escarlate」",
    "50": "「Gensokyo Escarlate」",
    "51": "Livro da Lua 「Selene Silenciosa」",
    "52": "Livro do Sol 「Erupção Magnificente」",
    "53": "Livro de Fogo Água Madeira Metal Terra 「Pedra Filosofal」",
    "54": "Tabu 「Armadilha Cranberry」",
    "55": "Tabu 「Lævateinn」",
    "56": "Tabu 「Trinca de Quatro」",
    "57": "Tabu 「Kagome, Kagome」",
    "58": "Tabu 「Labirinto do Amor」",
    "59": "Voleio Proibido 「Queda do Arco Estelar」",
    "60": "Voleio Proibido 「Catadióptrico」",
    "61": "Voleio Proibido 「Relógio que Deixa Passar o Passado」",
    "62": "Voleio Secreto 「E Então Não Sobrará Nenhum?」",
    "63": "C.Q.D. 「Repercussões de 495 Anos」"
}