{
    "0": "Magia Gelada 「Colunas Geladas」",
    "1": "Magia Gelada 「Colunas Geladas -Insano-」",
    "2": "Magia Fria 「Frio Duradouro -Fácil-」",
    "3": "Magia Fria 「Frio Duradouro」",
    "4": "Magia Fria 「Frio Duradouro -Difícil-」",
    "5": "Magia Fria 「Frio Duradouro -Insano-」",
    "6": "Magia Invernal 「Flor que se Murche -Fácil-」",
    "7": "Magia Invernal 「Flor que se Murche」",
    "8": "Magia Nevada 「Raio Sinuoso」",
    "9": "Magia Mística 「Virar o Jogo」",
    "10": "Feitiço Eremita 「Ovo de Fenghuang -Fácil-」",
    "11": "Feitiço Eremita 「Ovo de Fenghuang」",
    "12": "Feitiço Eremita 「Abrir de Asas do Fenghuang」",
    "13": "Feitiço Eremita 「Abrir de Asas do Fenghuang -Insano-」",
    "14": "Feitiço Shikigami 「O Vôo de Seimei -Fácil-」",
    "15": "Feitiço Shikigami 「O Vôo de Seimei」",
    "16": "Yin Yang 「Dōman-Seimei」",
    "17": "Yin Yang 「Seimei-Daimon」",
    "18": "Mandato do Céu 「Aquilo que Retumba em Tianxian -Fácil-」",
    "19": "Mandato do Céu 「Aquilo que Retumba em Tianxian」",
    "20": "Feitiço Voador 「O Vôo de Idaten」",
    "21": "Feitiço Serviçal 「A Dança Desordeira da Gohō-Tendō」",
    "22": "Feitiço Eremita 「Imortalidade Shikai -Fácil-」",
    "22": "Feitiço Eremita 「Imortalidade Shikai」",
    "24": "Feitiço Oni 「Portão Demoníaco do Konjin」",
    "25": "Feitiço Direcional 「Kimontonkou」",
    "26": "Performance da Titereira 「Bunraku da Donzela」",
    "27": "Performance da Titereira 「Bunraku da Donzela -Insano-」",
    "28": "Performance Azulada 「Bonecas Francesas Fraternais -Fácil-」",
    "29": "Performance Azulada 「Bonecas Francesas Fraternais」",
    "30": "Performance Azulada 「Bonecas Francesas Fraternais -Difícil-」",
    "31": "Performance Azulada 「Bonecas Fraternais de Orleans」",
    "32": "Performance Escarlate 「Bonecas Ruivas Neerlandesas -Fácil-」",
    "33": "Performance Escarlate 「Bonecas Ruivas Neerlandesas」",
    "34": "Performance Branca 「Bonecas Níveas Russas」",
    "35": "Performance Branca 「Bonecas Níveas Russas -Insano-」",
    "36": "Performance Sombria 「Bonecas de uma Londres Enevoada -Fácil-」",
    "37": "Performance Sombria 「Bonecas de uma Londres Enevoada」",
    "38": "Performance Cíclica 「Bonecas Tibetanas Samsáricas」",
    "39": "Performance Elegante 「Bonecas de uma Primavera em Quioto」",
    "40": "Praguejar 「Bonecas de Xangai Magicamente Luminosas -Fácil-」",
    "41": "Praguejar 「Bonecas de Xangai Magicamente Luminosas」",
    "42": "Praguejar 「Bonecas de Xangai Magicamente Luminosas -Difícil-」",
    "43": "Praguejar 「Bonecas de Hōrai Enforcadas」",
    "44": "Concerto Barulhento 「Clamor Fantasmagórico -Fácil-」",
    "44": "Concerto Barulhento 「Clamor Fantasmagórico」",
    "46": "Concerto Barulhento 「Poltergeist ao Vivo」",
    "47": "Concerto Barulhento 「Poltergeist ao Vivo -Insano-」",
    "48": "Solo de Violino 「Guarneri del Gesù -Fácil-」",
    "49": "Solo de Violino 「Guarneri del Gesù」",
    "50": "Violino Divino 「Stradivarius」",
    "51": "Violino Falso 「Pseudo Stradivarius」",
    "52": "Espírito do Trompete 「Hino Fantasmagórico -Fácil-」",
    "53": "Espírito do Trompete 「Hino Fantasmagórico」",
    "54": "Trompete do Além 「Fantasma de Clifford」",
    "55": "Trompete do Além 「Fantasma de Clifford -Insano-」",
    "56": "Teclas do Além 「Performance Póstuma do Fazioli -Fácil-」",
    "57": "Teclas do Além 「Performance Póstuma do Fazioli」",
    "58": "Espírito das Teclas 「Performance Divina do Bösendorfer」",
    "58": "Espírito das Teclas 「Performance Divina do Bösendorfer -Insano-」",
    "60": "Concerto Fúnebre 「Concerto Prisma -Fácil-」",
    "61": "Concerto Fúnebre 「Concerto Prisma」",
    "62": "Funeral Barulhento 「Margens do Estige」",
    "63": "Funeral Barulhento 「Margens do Estige -Insano-」",
    "64": "Grande Concerto Fúnebre 「Conc. Grosso da Roda Espiritual -Fácil-」",
    "65": "Grande Concerto Fúnebre 「Concerto Grosso da Roda Espiritual」",
    "66": "Grande Concerto Fúnebre 「Conc. Grosso da Roda Espiritual: Revisado」",
    "67": "Grande Concerto Fúnebre「Conc. Grosso da Roda Espiritual:Maravilhoso」",
    "68": "Espada Fantasma 「Jejum da Jovem Fantasma Faminta -Fácil-」",
    "69": "Espada Fantasma「Jejum da Jovem Fantasma Faminta」",
    "70": "Espada da Fantasma Faminta 「Pergaminho para o Mundo da Fantasma Faminta」",
    "71": "Espada Faminta do Rei 「A Retribuição de Dez Reis na Fantasma Faminta」",
    "72": "Espada do Mundo Infernal 「Duzentos Yojana em um Corte -Fácil-」",
    "73": "Espada do Mundo Infernal 「Duzentos Yojana em um Corte」",
    "74": "Espada do Fogo Infernal 「Corte do Vento Cármico da Súbita Formação Fantasma」",
    "75": "Espada do Deus Infernal 「Rasgo Divino Súbito do Vento Cármico」",
    "76": "Espada do Mundo dos Animais 「Punição Cármica dos Dispersos e Indolentes -Fácil-」",
    "77": "Espada do Mundo dos Animais 「Punição Cármica dos Dispersos e Indolentes」",
    "78": "Espada do Asura 「Obsessão com o Mundo Presente」",
    "79": "Espada do Asura 「Obsessão com o Mundo Presente -Insano-」",
    "80": "Espada do Mundo Humano 「Fantasia de Chegar ao Esclarecimento -Fácil-」",
    "81": "Espada do Mundo Humano 「Fantasia de Chegar ao Esclarecimento」",
    "82": "Espada da Era Humana 「O Grande Esclarecimento Aparecendo e Desaparecendo」",
    "83": "Espada do Deus Humano 「Constância da Verdade Convencional」",
    "84": "Espada do Paraíso 「Cinco Sinais do Deva Moribundo -Fácil-」",
    "85": "Espada do Paraíso 「Cinco Sinais do Deva Moribundo」",
    "86": "Espada do Mundo dos Devas 「Desprazer dos Sete Hakus」",
    "87": "Espada do Deus do Paraíso 「Três Kons, Sete Hakus」",
    "88": "Espada dos Seis Mundos 「Um Único Pens. e Infinitos Kalpas -Fácil-」",
    "89": "Espada dos Seis Mundos 「Um Único Pens. e Infinitos Kalpas」",
    "90": "Espada dos Seis Mundos 「Um Único Pens. e Infinitos Kalpas -Difícil-」",
    "91": "Espada dos Seis Mundos 「Um Único Pens. e Infinitos Kalpas-Insano-」",
    "92": "Perdendo a Cidade Natal 「A Morte do Lar de Alguém -Alma Errante-」",
    "93": "Losing Hometown 「Death of One's Home -Pecado no Passado-」",
    "94": "Losing Hometown 「Death of One's Home -Caminho Sem Rota-」",
    "95": "Losing Hometown 「Death of One's Home -Suicídio-」",
    "96": "Dança Fatal 「Regra da Mortalidade -Perplexidade-」",
    "97": "Dança Fatal 「Regra da Mortalidade -Borboleta Morta-」",
    "98": "Dança Fatal 「Regra da Mortalidade -Mariposa Venenosa-」",
    "99": "Dança Fatal 「Regra da Mortalidade -Mundo Demoníaco-」",
    "100": "Alma Florida 「Borboleta Fantasma」",
    "101": "Alma Florida 「Papilio machaon」",
    "102": "Alma Florida 「Borboleta Enraizada」",
    "103": "Alma Florida 「Delírio da Borboleta」",
    "104": "Melodia Sutil 「Repositório de Hirokawa -Espírito Falso-」",
    "105": "Melodia Sutil 「Repositório de Hirokawa -Espírito Morto-」",
    "106": "Melodia Sutil 「Repositório de Hirokawa -Espírito Fantasma-」",
    "107": "Melodia Sutil 「Repositório de Hirokawa -Espírito Divino-」",
    "108": "Assombração das Fl. de Cerej. 「Perfeita Fl. de Cerej. Preta -Selo-」",
    "109": "Assombração das Fl. de Cerej. 「Perfeita Fl. de Cerej. Preta -Auto-Perda-」",
    "110": "Assombração das Fl. de Cerej. 「Perfeita Fl. de Cerej. Preta -Sono Primaveril-」",
    "111": "Assombração das Fl. de Cerej. 「Perfeita Fl. de Cerej. Preta -Florescer-」",
    "112": "「Borboleta da Ressurreição -10%% do Reflorescimento-」",
    "113": "「Borboleta da Ressurreição -30%% do Reflorescimento-」",
    "114": "「Borboleta da Ressurreição -50%% do Reflorescimento-」",
    "115": "「Borboleta da Ressurreição -80%% do Reflorescimento-」",
    "116": "Marca Oni 「Oni Azul, Oni Vermelho」",
    "117": "Kishin 「O Vôo de Bishamonten」",
    "118": "Shikigami 「Meditação Contemplativa de Senko」",
    "119": "Shikigami 「Banquete dos Doze Deuses Generais」",
    "120": "Genialidade Shiki 「Laser da Yōkai Tanuki-Kitsune」",
    "121": "Genialidade Shiki 「Cerco Charmoso Vindo de Todos os Lados」",
    "122": "Genialidade Shiki 「Princesa Tenko -Ilusão-」",
    "123": "Tiro Shiki 「Budista Suprema」",
    "124": "Tiro Shiki 「Contato Unilateral」",
    "125": "Shikigami 「Chen」",
    "126": "「Contrato da Kokkuri-san」",
    "127": "Deus Ilusório 「Chegada de Izuna Gongen」",
    "128": "Shikigami 「Proteção de Zenki e Goki」",
    "129": "Shikigami 「Canalizando Dakiniten」",
    "130": "Barreira 「Maldição dos Sonhos e da Realidade」",
    "131": "Barreira 「Equilíbrio da Ação e Inação」",
    "132": "Barreira 「Mistura da Luz e Escuridão」",
    "133": "Espíritos Malignos 「Terra dos Sonhos da Curva e a Reta」",
    "134": "Espíritos Malignos 「Kamikakushi da Yukari Yakumo」",
    "135": "Espíritos Malignos 「Borboleta Enfeitiçada Vivendo em um Templo Zen」",
    "136": "Espíritos Sinistros 「Morte Negra Dupla da Borboleta」",
    "137": "Shikigami 「Ran Yakumo」",
    "138": "「Divisa entre os Humanos e Yōkai」",
    "139": "Barreira 「Divisa entre Vida e Morte」",
    "140": "Yukari Arcanum 「Barreira Danmaku」",
}